name: 自动构建与部署

on:
  push:
    branches: [ "main" ] # 监听 main 分支的提交

jobs:
  build:
    runs-on: ubuntu-latest # 使用 GitHub 提供的 Linux 服务器

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 安装依赖
      run: npm install

    - name: 执行构建
      run: npm run build || true
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: my-project-dist  # 这是你下载时的压缩包名字
        path: dist/            # 这里填构建生成的文件夹名称，Vue 通常是 dist
